all:
  vars:
    ansible_remote_tmp: /tmp
  hosts:
    frr-as65001:
      ansible_connection: docker
      ansible_host: frr-as65001
    frr-as65002:
      ansible_connection: docker
      ansible_host: frr-as65002
